/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab08;

/**
 *
 * @author Plywak
 */
public class Calc extends javax.swing.JFrame {

    /**
     * Creates new form Calc
     */
    public Calc() {
        initComponents();
    }
    public String num="";
    int opt=0,res=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void calc(){
        switch(opt){
            case 1:
                res=Integer.parseInt(num)+Integer.parseInt(screen.getText());
                screen.setText(Integer.toString(res));
                break;
            case 2:
                res=Integer.parseInt(num)-Integer.parseInt(screen.getText());
                screen.setText(Integer.toString(res));
                break;
            case 3:
                if(Integer.parseInt(screen.getText())!=0){
                    res=Integer.parseInt(num)/Integer.parseInt(screen.getText());
                    screen.setText(Integer.toString(res));
                }
                else screen.setText("ERROR DIV BY 0 IS NOT POSSIBLE");
                break;
            case 4:
                res=Integer.parseInt(num)*Integer.parseInt(screen.getText());
                screen.setText(Integer.toString(res));
                break;
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j1 = new javax.swing.JButton();
        j4 = new javax.swing.JButton();
        j7 = new javax.swing.JButton();
        j2 = new javax.swing.JButton();
        j5 = new javax.swing.JButton();
        j8 = new javax.swing.JButton();
        j3 = new javax.swing.JButton();
        j6 = new javax.swing.JButton();
        j9 = new javax.swing.JButton();
        j10 = new javax.swing.JButton();
        j11 = new javax.swing.JButton();
        j12 = new javax.swing.JButton();
        j13 = new javax.swing.JButton();
        j14 = new javax.swing.JButton();
        j0 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        screen = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        j1.setText("1");
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch1(evt);
            }
        });

        j4.setText("4");
        j4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch4(evt);
            }
        });

        j7.setText("7");
        j7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch7(evt);
            }
        });

        j2.setText("2");
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch2(evt);
            }
        });

        j5.setText("5");
        j5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch5(evt);
            }
        });

        j8.setText("8");
        j8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch8(evt);
            }
        });

        j3.setText("3");
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch3(evt);
            }
        });

        j6.setText("6");
        j6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch6(evt);
            }
        });

        j9.setText("9");
        j9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch9(evt);
            }
        });

        j10.setText("+");
        j10.setMaximumSize(new java.awt.Dimension(39, 23));
        j10.setMinimumSize(new java.awt.Dimension(39, 23));
        j10.setPreferredSize(new java.awt.Dimension(39, 23));
        j10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add(evt);
            }
        });

        j11.setText("-");
        j11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                substract(evt);
            }
        });

        j12.setText("/");
        j12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divide(evt);
            }
        });

        j13.setText("*");
        j13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiply(evt);
            }
        });

        j14.setText("=");
        j14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eq(evt);
            }
        });

        j0.setText("0");
        j0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch0(evt);
            }
        });

        screen.setEditable(false);
        screen.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(screen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(j7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(j8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(j4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(j5))
                            .addComponent(j0, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(j12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j13, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(j2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j1)
                    .addComponent(j2)
                    .addComponent(j3)
                    .addComponent(j10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j4)
                    .addComponent(j5)
                    .addComponent(j6)
                    .addComponent(j11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j7)
                    .addComponent(j8)
                    .addComponent(j9)
                    .addComponent(j12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j13)
                    .addComponent(j14)
                    .addComponent(j0))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ch1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch1
        // TODO add your handling code here:
        screen.setText(screen.getText()+"1");
    }//GEN-LAST:event_ch1

    private void ch4(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch4
        // TODO add your handling code here:
        screen.setText(screen.getText()+"4");
    }//GEN-LAST:event_ch4

    private void ch7(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch7
        // TODO add your handling code here:
        screen.setText(screen.getText()+"7");
    }//GEN-LAST:event_ch7

    private void ch2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch2
        // TODO add your handling code here:
        screen.setText(screen.getText()+"2");
    }//GEN-LAST:event_ch2

    private void ch5(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch5
        // TODO add your handling code here:
        screen.setText(screen.getText()+"5");
    }//GEN-LAST:event_ch5

    private void ch8(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch8
        // TODO add your handling code here:
        screen.setText(screen.getText()+"8");
    }//GEN-LAST:event_ch8

    private void ch3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch3
        // TODO add your handling code here:
        screen.setText(screen.getText()+"3");
    }//GEN-LAST:event_ch3

    private void ch6(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch6
        // TODO add your handling code here:
        screen.setText(screen.getText()+"6");
    }//GEN-LAST:event_ch6

    private void ch9(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch9
        // TODO add your handling code here:
        screen.setText(screen.getText()+"9");
    }//GEN-LAST:event_ch9

    private void add(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add
        // TODO add your handling code here:
        num=screen.getText();
        opt=1;
        screen.setText("");
    }//GEN-LAST:event_add

    private void substract(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_substract
        // TODO add your handling code here:
        num=screen.getText();
        opt=2;
        screen.setText("");
    }//GEN-LAST:event_substract

    private void divide(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divide
        // TODO add your handling code here:
        num=screen.getText();
        opt=3;
        screen.setText("");
    }//GEN-LAST:event_divide

    private void multiply(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiply
        // TODO add your handling code here:
        num=screen.getText();
        opt=4;
        screen.setText("");
    }//GEN-LAST:event_multiply

    private void eq(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eq
        // TODO add your handling code here:
        calc();
        screen.setText(screen.getText());
    }//GEN-LAST:event_eq

    private void ch0(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch0
        // TODO add your handling code here:
        screen.setText(screen.getText()+"0");
    }//GEN-LAST:event_ch0

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton j0;
    private javax.swing.JButton j1;
    private javax.swing.JButton j10;
    private javax.swing.JButton j11;
    private javax.swing.JButton j12;
    private javax.swing.JButton j13;
    private javax.swing.JButton j14;
    private javax.swing.JButton j2;
    private javax.swing.JButton j3;
    private javax.swing.JButton j4;
    private javax.swing.JButton j5;
    private javax.swing.JButton j6;
    private javax.swing.JButton j7;
    private javax.swing.JButton j8;
    private javax.swing.JButton j9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane screen;
    // End of variables declaration//GEN-END:variables
}
