/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.dbreports;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Properties;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;

/**
 *
 * @author Plywak
 */
public class genReports extends javax.swing.JFrame {

    /**
     * Creates new form genReports
     */
    public genReports() {
        initComponents();
    }
    public int sqlOpt;
    public String sqlParams;
    public void genRepo(String name,int sqlOpt){
        String[] sql={"SELECT \"ID_dostawca\",\"Dostawcy\".\"Nazwa\",\"Dostawy\".\"ID_dostawa\",\"Bukiety\".\"Nazwa\",\"Dostawy_bukietów\".\"Ilość\",\"Wartość\",\"Data_dostawy\"-\"Data_złożenia\" AS czas_dst\n" +
"FROM \"Dostawcy\"\n" +
"INNER JOIN \"Dostawy\" USING(\"ID_dostawca\")\n" +
"INNER JOIN \"Dostawy_bukietów\" ON \"Dostawy_bukietów\".\"ID_dostawy\"=\"Dostawy\".\"ID_dostawa\"\n" +
"INNER JOIN \"Bukiety\" ON \"Bukiety\".\"ID_bukiet\"=\"Dostawy_bukietów\".\"ID_bukiet\""+sqlParams,
        "SELECT \"ID_bukiet\",\"Bukiety\".\"Nazwa\",\"Kwiaty_słownik\".\"Nazwa\",\"Ilość\",\"Kolor\" FROM \"Bukiety_kwiaty\" INNER JOIN \"Bukiety\" USING(\"ID_bukiet\") INNER JOIN \"Kwiaty_słownik\" USING (\"ID_kwiat\")"+sqlParams,
        "SELECT SUM(\"Zamówienia_bukiety\".\"Ilość_sztuk\")AS il_sprzedanych,\"Bukiety\".\"Nazwa\",SUM(\"Zamówienia_bukiety\".\"Wartość\") FROM \"Bukiety\"\n" +
"INNER JOIN \"Zamówienia_bukiety\" USING (\"ID_bukiet\")\n" +
"INNER JOIN \"Zamówienia\" ON \"Zamówienia_bukiety\".\"ID_zamówienia\"=\"Zamówienia\".\"ID_zamówienia\"\n"+sqlParams,
        "SELECT COUNT(\"ID_zamówienia\")AS il_zam,SUM(\"Suma\")AS suma,\"Pracownicy\".imie,  \"Pracownicy\".nazwisko,\"ID_pracownik\",\"ID_szef\"\n" +
"FROM \"Zamówienia\"\n" +
"INNER JOIN \"Pracownicy\" USING(\"ID_pracownik\")\n"+sqlParams};
        try {
            Class.forName("org.postgresql.Driver");
            String url = "jdbc:postgresql://localhost/Kwiaciarniav2";
            Properties props = new Properties();
            props.setProperty("user","postgres");
            props.setProperty("password","Qwerty123456");
            Connection con = DriverManager.getConnection(url, props);
            Statement sql1=con.createStatement();
            JRDataSource jrDS = new JRResultSetDataSource(sql1.executeQuery(sql[sqlOpt]));
            JasperReport jR = JasperCompileManager.compileReport("C:\\Users\\Plywak\\JaspersoftWorkspace\\MyReports\\"+name+".jrxml");
            JasperPrint jP = JasperFillManager.fillReport(jR, new HashMap(), jrDS);
            JasperExportManager.exportReportToPdfFile(jP, "C:\\Users\\Plywak\\JaspersoftWorkspace\\MyReports\\"+name+".pdf");
	} catch (Exception e) {
		e.printStackTrace();
		System.err.println(e.getClass().getName()+": "+e.getMessage());
	}
        System.out.println("Wygenerowano");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DeliveryYearFrom = new javax.swing.JTextField();
        DeliveryMonFrom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Flowers = new javax.swing.JTextField();
        Colour = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Amount = new javax.swing.JTextField();
        SumYear = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        SalesYear = new javax.swing.JTextField();
        SalesMonth = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        IDszef = new javax.swing.JTextField();
        MinSales = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        DeliveryYearTo = new javax.swing.JTextField();
        DeliveryMonTo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Generator raportów Jasper z bazy danych Kwiaciarnia");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Deliveries", "BouqetsFlowers", "KwiaciarniaRepoSells", "KwiaciarniaSellsBySalesperson" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);
        jList1.getAccessibleContext().setAccessibleName("");

        jLabel2.setText("Wybierz raport");

        jLabel3.setText("Raport: Deliveries");

        jLabel5.setText("Raport: BouqetFlowers");

        jLabel6.setText("Raport: KwiaciarniaRepoSells");

        jLabel7.setText("Raport: KwiaciarniaSalesBySalesperson");

        DeliveryYearFrom.setText("2017");
        DeliveryYearFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveryYearFromActionPerformed(evt);
            }
        });

        DeliveryMonFrom.setText("1");

        jLabel8.setText("Wybierz rok:");

        jLabel9.setText("Wybierz miesiąc:");

        jLabel10.setText("Wybierz min ilość kwiatów w bukiecie:");

        jLabel11.setText("Wybierz jaki kolor ma być dostępny");

        Flowers.setText("1");
        Flowers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlowersActionPerformed(evt);
            }
        });

        Colour.setText("Kolor");

        jLabel12.setText("Wybierz min ilość sprzedanych sztuk");

        jLabel13.setText("Wybierz rok do podsumowania");

        Amount.setText("1");

        SumYear.setText("2017");
        SumYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumYearActionPerformed(evt);
            }
        });

        jLabel14.setText("Wybierz rok:");

        jLabel15.setText("Wybierz miesiąc:");

        SalesYear.setText("2017");

        SalesMonth.setText("1");

        jLabel16.setText("Wybierz ID szefa:");

        jLabel17.setText("Wybierz min kwotę sprzedaży:");

        IDszef.setText("2");

        MinSales.setText("100");

        jButton1.setText("Generuj raport");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel18.setText("Wybierz rok:");

        jLabel19.setText("Wybierz miesiąc:");

        DeliveryYearTo.setText("2017");
        DeliveryYearTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveryYearToActionPerformed(evt);
            }
        });

        DeliveryMonTo.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        DeliveryMonTo.setText("12");

        jLabel20.setText("DO->");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DeliveryYearFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DeliveryMonFrom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel12))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SumYear)
                                    .addComponent(Amount)))
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(jLabel14))
                                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(SalesYear)
                                        .addComponent(SalesMonth))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(jLabel16))
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(IDszef, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MinSales, javax.swing.GroupLayout.Alignment.LEADING))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(jLabel18))
                                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(DeliveryYearTo)
                                        .addComponent(DeliveryMonTo))
                                    .addGap(91, 91, 91)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel10))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Colour, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Flowers, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton1)))
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DeliveryYearFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DeliveryMonFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DeliveryYearTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DeliveryMonTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel20)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Flowers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Colour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SumYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SalesYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SalesMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDszef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MinSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeliveryYearFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveryYearFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeliveryYearFromActionPerformed

    private void FlowersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlowersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FlowersActionPerformed

    private void SumYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SumYearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String RepoOpt=jList1.getSelectedValue();
        switch (RepoOpt){
            case "Deliveries":
                sqlOpt=0;
                sqlParams="WHERE (EXTRACT(YEAR FROM \"Data_dostawy\") BETWEEN "+Integer.parseInt(DeliveryYearFrom.getText())+" AND "+Integer.parseInt(DeliveryYearTo.getText())+") AND (EXTRACT(MONTH FROM \"Data_dostawy\") BETWEEN "+Integer.parseInt(DeliveryMonFrom.getText())+" AND "+Integer.parseInt(DeliveryMonTo.getText())+")";
                System.out.println("Wybrany z listy:"+jList1.getSelectedValue()+" | "+sqlParams);
                break;
            case "BouqetsFlowers":
                sqlOpt=1;
                if(Colour.getText().equals("")){
                    sqlParams="WHERE \"Ilość\">"+Integer.parseInt(Flowers.getText());
                }
                else{
                    sqlParams="WHERE \"Ilość\">"+Integer.parseInt(Flowers.getText())+" AND '"+Colour.getText()+"'=ANY(\"Kolor\")";
                }
                System.out.println("Wybrany z listy:"+jList1.getSelectedValue()+" | "+sqlParams);
                break;
            case "KwiaciarniaRepoSells":
                sqlOpt=2;
                sqlParams="WHERE EXTRACT(YEAR FROM \"Data_złożenia\")="+Integer.parseInt(SumYear.getText())+"GROUP BY \"ID_bukiet\""+" HAVING SUM(\"Zamówienia_bukiety\".\"Ilość_sztuk\")>"+Integer.parseInt(Amount.getText());
                System.out.println("Wybrany z listy:"+jList1.getSelectedValue()+" | "+sqlParams);
                break;
            case "KwiaciarniaSellsBySalesperson":
                sqlOpt=3;
                if(Integer.parseInt(IDszef.getText())!=2 || Integer.parseInt(IDszef.getText())!=3){
                    sqlParams="WHERE \"ID_klient\"<>0  AND EXTRACT(YEAR FROM \"Data_złożenia\")="+Integer.parseInt(SalesYear.getText())+" AND EXTRACT(MONTH FROM \"Data_złożenia\")="+Integer.parseInt(SalesMonth.getText())+" GROUP BY \"ID_pracownik\",\"imie\",\"nazwisko\",\"ID_szef\" HAVING SUM(\"Suma\")>"+Double.parseDouble(MinSales.getText())+"";
                }
                else{
                    sqlParams="WHERE \"ID_klient\"<>0  AND EXTRACT(YEAR FROM \"Data_złożenia\")="+Integer.parseInt(SalesYear.getText())+" AND EXTRACT(MONTH FROM \"Data_złożenia\")="+Integer.parseInt(SalesMonth.getText())+" AND \"ID_szef\"="+Integer.parseInt(IDszef.getText())+" GROUP BY \"ID_pracownik\",\"imie\",\"nazwisko\",\"ID_szef\" HAVING SUM(\"Suma\")>"+Double.parseDouble(MinSales.getText())+"";
                }
                System.out.println("Wybrany z listy:"+jList1.getSelectedValue()+" | "+sqlParams);
                break;
        }
        genRepo(RepoOpt,sqlOpt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DeliveryYearToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveryYearToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeliveryYearToActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(genReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(genReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(genReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(genReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new genReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Amount;
    private javax.swing.JTextField Colour;
    private javax.swing.JTextField DeliveryMonFrom;
    private javax.swing.JTextField DeliveryMonTo;
    private javax.swing.JTextField DeliveryYearFrom;
    private javax.swing.JTextField DeliveryYearTo;
    private javax.swing.JTextField Flowers;
    private javax.swing.JTextField IDszef;
    private javax.swing.JTextField MinSales;
    private javax.swing.JTextField SalesMonth;
    private javax.swing.JTextField SalesYear;
    private javax.swing.JTextField SumYear;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
